language: python

python:
  - 2.7

install:
  - pip install -r dev-requirements.txt

script:
  - make clean
  - make check
  - make pep8
  - make pyflakes
  - make pylint
  - make unittest
  - make coverage_report

notifications:
  email:
    - cwomble@arista.com

after_success:
  codecov
